services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_DB: ${POSTGRES_DB:-nest-clean}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
